language: ruby
sudo: false
cache: bundler
rvm: 
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3

bundler_args: --without development
script: bundle exec rake spec SPEC_OPTS='--format documentation'
